### ISSUE TITLE
EKF Localization

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#11]
Working with EKF issues owner, move feature selection methods to a good folder in environments, then redo examples to use EKF function, and motion and measurement models.  Test multiple configurations.

**Comment by yshiyi** [comment]
Dear Prof,
I'd like to assign this issue, but I am not sure what I should do.
Should I implement the feature selection methods to those files in environments?
Thank you.

**Comment by ghost** [comment]
I think there might be some confusion on this topic. I signed up for this topic last week (just by creating a branch) and actually just committed some of my changes. Not sure how to proceed.

Regards,

Rhyse

**Comment by stevenwaslander** [comment]
That sounds great, make the feature measurement models functions and store them in the sensors folder, then try to remake the example with an environment you put in the environments folder.  Feel free to change the example.

**Comment by yshiyi** [comment]
Sorry, Rhyse.
I didn't notice that you have already signed up this issue, since it shows this issue is still available.

**Comment by ghost** [comment]
Dr. Waslander,

What exactly did you mean by "move feature selection methods to a good folder in environments"? The environment is a number of 2D points which is held in an array. I am not sure how this should be implemented in function form.

Thanks,

Rhyse

**Comment by chutsu** [comment]
I believe the environments folder Prof Waslander is referring to is the `10-environments` folder, with feature selection, there are a couple of functions that can be generalized such as `inview()` or `closestfeature()` that can be placed there. 

But on second thought, I think he might have changed his mind, and the `sensors` folder is a better place to place these functions into.  Hope that helps

**Comment by stevenwaslander** [comment]
Second thought, yes, I see the inview and closestfeature functions as parts of the sensor models, and the other stuff that defines feature locations as part of the environments.

**Comment by ghost** [comment]
@stevenwaslander One thing I noticed when working on the code is that the localization is only done with respect to 1 map feature, even when multiple features are in view. Would you be interested in implementing some sort of code which is able to better refine the state prediction if multiple features are in view?

**Comment by stevenwaslander** [comment]
Yikes! Is it only one map feature, or only one map feature at a time, but looping through all visible features at each timestep.  Remember we are allowed to update the EKF one set of feature measurements at a time.

**Comment by ghost** [comment]
It makes sense that we can update the state estimate with each feature measurement, but the thing is I don't see how the code was previously doing that

The starting code I was provided with does loop through all visible features, but only the results from the last iteration are stored. Looking through the code I see the following algorithm.

For each time step:
-Calculate the predicted mean and covariance, store these values as mup and Sp respectively.
-For loop going through all features, if the feature is in view do the following:
     -Calculate kalman gain, updated state, and updated covariance. (but these values are not stored                between iterations. The loop just goes to the next feature in view and calculates the same values using mup and Sp. The final value for mu and S that is stored is done so after the for loop, which is just the most recently completed run

If multiple features were being used to update the state prediction I would expect that the covariance matrix prediction would be refined between each subsequent feature measurement. Because I assumed that only one feature was being used I wrote my code to only consider 1 feature per time step and I get similar performance.

Can you please let me know if

 I am missing something? I have gone through the code a number of times but may not be seeing something.

Thanks

[Prediction update.pdf](https://github.com/WaterlooRobotics/mobilerobotics/files/160046/Prediction.update.pdf)
