### ISSUE TITLE
EKF

### ISSUE THREAD

**Issue by stevenwaslander** [WaterlooRobotics/mobilerobotics#7]
The EKF should be a function that uses motion and measurement models and their derivatives.  Needs to work with RANSAC, SLAM, Localization.

**Comment by ghost** [comment]
Hi Brent,

I am working on the EKF localization and just wanted to confirm how I should incorporate your work. For EKF localization I see the following:
-IN: Function handle for motion model, prior state prediction, prior co variance matrix, function handle for measurement model, Q, and R disturbance models
-OUT: updated state, updated co variance matrix

Maybe something like this http://www.mathworks.com/matlabcentral/fileexchange/18189-learning-the-extended-kalman-filter

Let me know what you think.

**Comment by bjkomer** [comment]
I haven't finished it yet, but that sounds a lot like the kind of inputs and outputs I'm expecting to make.

**Comment by bjkomer** [comment]
@rhyse-me780 I've finished the function now, you can see how it works on my branch and/or pull request. The main difference in inputs from what you mentioned above is that is also takes in a measurement as well as function handles for both the linearized and nonlinearized models (because the mean can go through the nonlinear one).

Let me know if there is anything that needs to get changed to work with your code.

**Comment by stevenwaslander** [comment]
Nice work guys!

**Comment by ghost** [comment]
@bjkomer I've begun integrating your code and have noticed one change I would recommend. Both the non-linear and linear motion model have inputs u(t) as well as previous states.

**Comment by stevenwaslander** [comment]
Agreed!

**Comment by bjkomer** [comment]
Good call. The example I was working with didn't use u so I forgot about it. I've added it now, and also allowed the sensor models to use it, since technically they are allowed to as well, even though it is rare.
